### ISSUE TITLE
Create video footage for tutorials/features/tech demo

### ISSUE THREAD

**Issue by adamkewley** [ComputationalBiomechanicsLab/opensim-creator#127]
This is a general ticket for creating video footage for OpenSim Creator.

Because an upcoming workshop is spanning 7-9 timezones, we need to deliver *a lot* of content asynchronously in the form of written tutorial documentation and videos. The written documentation is already there, but I need to record video versions of each tutorial (ideally) and video versions of more overview-ey content ("here's opensim creator, here's some key features").

I am not especially experienced in video creation, but have done it a little bit before. I can *probably* deliver some passable-quality video tutorials over the next few days in-time for workshop, which should hopefully provide NA attendees enough to chew on while we're asleep in EU.

Video recording priority is:

- Tutorial 3/4 - these are key tutorials that introduce the mesh importer, which is assumed to be an important part of the software
- General feature overview video - introduce things like hot reloading, model editing, output plotting, etc. - things that aren't necessarily automatically obvious
- Tutorial 1/2 - less-important videos but still likely to be useful for people wanting to see how to add components to models etc.
- Meta workshop video - overview of the workshop, what platforms we're using (discord, email, whatever), where to find materials, how to approach the workshop
- Tech demo - for general distribution across the internet: "it's here and you should try it out"

Tasks:

- [x] Record rough tutorial 3 video
- [ ] Get feedback on rough video
- [ ] Re-record tutorial 3 video (if necessary)
- [ ] Perform post-production on tutorial 3 video (title slides, transitions, captions, etc.)
- [x] Record rough tutorial 4 video
- [ ] Get feedback on tutorial 4 video
- [ ] Perform post-production on tutorial 4 video (title slides, transitions, captions, etc.)
- [x] Record overview video
- [x] Record tutorial 1 video
- [x] Record tutorial 2 video

**Comment by adamkewley** [comment]
The first rough recording of tutorial 3 is out:

https://www.youtube.com/watch?v=RBue8pm6mC8

Provide any feedback on audio quality, speed, crappy northern-England accent, etc. where appropriate here, or whisper me (if you think I'd take it harshly on a public forum ;))

**Comment by itbellix** [comment]
Hi @adamkewley, the video looks really nice! The northern-England accent is completely understandable (to me at least), and I think it is a great guide through the tutorial. It is unfortunate that the scaling of the cubes at a certain point did not really work interactively, but I really don't think it is a problem.

I also think that the speed is appropriate, even a bit faster would be nice but since I kind of know the tutorial already I am probably a bit biased!

As a last thing, maybe for the next videos it would be nice to cut it in part1-part2 or something like that, just to increase the *appeal* (let's call it like that) on people who might stumble in it. A shorter video (like 10 minutes) is probably more catchy, and once you start it you are also very likely to keep watching part2 as well 😃

**Comment by adamkewley** [comment]
@itbellix thanks for watching it through! :smile: - it's good to know that the most important thing (that people can understand the content) is at least covered, even if the video timing/editing could do some work

The cube rescaling thing did suck, yeah :<. Unfortunately, because I'm fairly time-constrained, I haven't had much of a chance to learn how to make decent cuts (e.g. in windows movie maker, DaVinci Resolve, whatever editing software), so I'm currently relying on doing single-take tutorial runs for this first round. Hopefully, there will be time to re-record or edit some of them before Tuesday, though.

You're right, though, the best format would be shorter 10-20min videos with proper editing. If I get the time after we ship the first batch of top-priority videos, I'll try to re-record the footage with more of a script, time limits, parts, basic editing (captions, etc.)

**Comment by adamkewley** [comment]
The tutorial 4 draft video is now also available (youtube might take a second to produce the HD version)

https://www.youtube.com/watch?v=EWcMT99_nf0

The video is 45min long, which I know is less-than-ideal (sorry @itbellix ), but I've tried to ensure that the video also covers a lot of tricks and tips for using OpenSim Creator (hotkeys, going through things very slowly).

For context, the reason why this tutorial a bit meatier is because this video is intended to fully prep workshop attendees for creating "proper" (i.e. not just a pendulum) models. After watching this video, they need to feel extremely comfortable with adding bodies, adding joints, etc. - even to the point of boredom.

There's also a lot of rambling about not-quite-tutorial-related stuff, like viewing the file in OpenSim GUI and editing it in a text editor. This is because I'm poor at sticking to the script. However, I also guessed that unfamiliar attendees might want to know a trick or two for dealing with the overall "ecosystem" and any "workarounds" (e.g. editing the file in a text editor) from this video - even if I'm going to **also** redundantly record other videos mentioning the same features (I'm relying on the controversial ideology of: "the key to teaching is repetition repetition repetition").

**Comment by itbellix** [comment]
HI @adamkewley, I like this video too! Don't worry, my opinion about the duration was a general one, not meant for rushing you even more in the days before the workshop.

I opened #130 after watching the video, it is an idea not related to this issue so I thought it was better to separate different things.

**Comment by adamkewley** [comment]
The (extremely rough) overview video is now online:

https://www.youtube.com/watch?v=QdFV4ompxE8

It's my first time editing separate clips in a while, so it's a bit janky. However, I feel that it probably gets the point across well-enough for the workshop. I can try and tweak it later if I get time after publishing the Tutorial 1 and Tutorial 2 videos.

**Comment by adamkewley** [comment]
Tutorials 1 and 2 now have basic tutorial videos:

- Tutorial 1 (19 min): https://www.youtube.com/watch?v=Fin8-_kVolg
- Tutorial 2 (25 min): https://www.youtube.com/watch?v=EOjib40vd-8

The footage is longer than an ideal YouTube video length, but I'm very short on time right now (it takes some amount of time to plan the video script, break it into parts, edit cuts, etc.) - the official v1.0 release of OpenSim Creator will probably require some re-recording and editing.

Tutorials 1 & 2 went off mostly without a hitch, but there were a couple of moments where I screwed up the undo/redo step (or maybe it was a bug of some sort). I kept that in because I didn't want to re-record/edit it and it was only a 30-second problem. Again, the footage will probably need a re-record and edit when we move toward a 1.0 release.

**Comment by adamkewley** [comment]
@itbellix thanks for your help with watching the videos etc.

The video footage is all uploaded and put into a playlist now:

 - https://www.youtube.com/watch?v=QdFV4ompxE8&list=PLOPlDtRLhp8c2SWLCQKKd-l4__UainOYk

The footage has some issues/quirks, but should be good enough for our immediate needs (the workshop). The main purpose of the footage right now is to replace what would've been done synchronously, had the workshop been delivered in-person or in a smaller timezone range. The 1.0 footage should probably be higher quality, though :)

Thanks again

**Comment by itbellix** [comment]
Hi @adamkewley, thank you! 
Also the new videos are very useful :)
