### ISSUE TITLE
Outdated name in Tutorial 1 Documentation

### ISSUE THREAD

**Issue by itbellix** [ComputationalBiomechanicsLab/opensim-creator#138]
Hi @adamkewley,
I am setting this as low priority, since it is not really crucial. 
I am going through [Tutorial 1](file:///C:/Program%20Files/OpenSimCreator/share/doc/html/tut1.html), and I see that in the following image it is mentioned to select the `Brick` geometry:
<img src='https://user-images.githubusercontent.com/50029203/153622233-ec844257-3906-4e70-8e6c-f9ee597cbb5f.png' width=450>

However, such a geometry appears not to exist anymore in the default suggestions (I believe it should now be `box` or  `cube`).

I will report here if there are other inaccuracies.

**Comment by itbellix** [comment]
Again, just for the sake of completeness, I report here that I followed the tutorial by setting the translation values indicated there (+1 along Y for the pendulum base and +0.5 along Y for the pendulum head). However, without touching the scale factors for the meshes (I used `box` and `sphere`), the whole scene looks like this:
<img src='https://user-images.githubusercontent.com/50029203/153625241-f6bc3e74-b571-4cd8-893a-e2e915e63502.png' width=450>
Is it possible that the dimensions of the meshes changed somehow from when this tutorial was written?
Maybe I am just doing something wrong, I am not sure!

**Comment by adamkewley** [comment]
It's entirely possible that I instinctively scaled the meshes down without actually writing that up in the documentation. 

I'll try and hotfix these documentation bugs in before Tuesday because, yeah, new users aren't going to know to rescale it - great spot! @itbellix

**Comment by itbellix** [comment]
Nice @adamkewley ! I believe that this fix would also improve the documentation of Tutorial 2, that is also based on the same objects (again, `brick` is mentioned but I cannot find a mesh named like that). I had some difficulties in it since I believe that you assume the radius of the `sphere` to be 0.1, while in my case it is 0.5 if I do not edit anything myself. Also the other indications regarding forces and springs were a little bit difficult to follow because of this, in my opinion

**Comment by itbellix** [comment]
HI @adamkewley, I just watched the new videos for Tutorial 1 and 2 (https://www.youtube.com/watch?v=Fin8-_kVolg&list=PLOPlDtRLhp8c2SWLCQKKd-l4__UainOYk&index=2), and I see that actually I was doing things wrong. I was choosing `mesh file` instead of `Generated geometry` in the pop up menu:
![image](https://user-images.githubusercontent.com/50029203/153835018-b1975c89-ff33-4264-835a-f32f1fccc2c6.png)

So, I guess a very quick fix to the documentation could be to mention where to find those meshes that you need to use in the tutorial itself

**Comment by adamkewley** [comment]
Crossref-d this from an issue that concretely addresses the basic fix (changing the documentation) - thanks for the report @itbellix
