### ISSUE TITLE
Report questions/discussions of OSC workshop

### ISSUE THREAD

**Issue by itbellix** [ComputationalBiomechanicsLab/opensim-creator#142]
Hi @adamkewley, you can just ignore this and re-write it as you find best, but I will just drop here the notes that I took today (and update them as we go, if it is useful).

**Comment by itbellix** [comment]
OSC NOTES

* bug/problem
- question
o note

15 Feb

* Problem opening .osim file from OSC (with Atom as default app, on Windows (?))
- Is it possible to load different meshes from the same .obj file?
- Is it possible to add wrapping obects in OSC?
- if I open a model in OSC and I go in import meshes and add an existing .osim file, it is not imported completely correctly
* .xml does not get updated for relative path for the model
- describe joints by using functions/equations (inside the .xml file, in the old SIMM files at the bottom,
  inputing a function when the joint is created)

**Comment by adamkewley** [comment]
Thanks for noting these @itbellix . I've put them into appropriate issues for later scheduling and I'll close this top-level aggregate issue:

- Adding wrapping support into the UI (an ancient issue that's been de-prioritized a bunch): #7 
- Rewording importing existing osim files to make it clear that they can be imported incorrectly #143
- Make mesh importer try to use relative paths to meshes, if possible, to make things easier to share between computers #144
- Investigate tooling for function-/equation-driven joints #145
