### ISSUE TITLE
Add basic ScapulothoracicJoint support

### ISSUE THREAD

**Issue by adamkewley** [ComputationalBiomechanicsLab/opensim-creator#334]
Add a custom decoration generator that generates an ellipsoid for the scapulothoracic joint.

**Comment by adamkewley** [comment]
@JuliaVanBeesel ellipsoid visualization for `ScapulothoracicJoint` is now implemented in the repository (not released yet). You can grab a continuous-integration release from the `Actions` page once (and if) it has been successfully built (the dots next to the commits, above, indicate the status of each build).

The visualization looks something like this:

![scapulo visualization](https://user-images.githubusercontent.com/4730570/182773663-79967b2d-f182-4434-b269-f475e5a85909.png)

And must be manually enabled via a checkbox in the scene menu. The reason it isn't done automatically is because I implemented it quickly and some people may already have other debug geometry in their model files (e.g. wrap surfaces) that overlap with this new visualization.

**Comment by adamkewley** [comment]
Additionally, I found that one way to make visualization easier was to:

- Toggle frames (`Edit -> Toggle Frames`), so I can see all frames
- Select the joint (now clickable in the viewport, if you enable this feature)
- Go to the properties window down to `sockets`
- Right-click the `child_frame` button (e.g. right-click `scapula_offset`)
- Start playing with the coordinates

This will select and rim-highlight the child frame of the joint, as you move it around. It might make it easier to see what it's doing:

![scapulo visualization_selection](https://user-images.githubusercontent.com/4730570/182775401-5304e6c9-f4af-4268-bd02-16566d4f06c8.png)

**Comment by JuliaVanBeesel** [comment]
> Thank you @adamkewley! This is amazing! And so utterly helpful! Thanks so much!!!

**Comment by adamkewley** [comment]
This is done for now - closing
