### ISSUE TITLE
Fix coordinate editor jumps around with heavily constrained models

### ISSUE THREAD

**Issue by adamkewley** [ComputationalBiomechanicsLab/opensim-creator#345]
This is to fix an annoying user-facing issue that is at its worst when the model contains constraints.

The buggy behavior is this:

- Open a more complicated model containing constraints that conceivably move joint locations around *a lot* compared to their current/default value (e.g. because two parts of a joint frame are constrained to be colocated or similar)
- Try to edit a coordinate that exercises the constraint
- The coordinate editor will show everything moving smoothly (fine), but will "snap" to a different configuration when the user lets go of the mouse

The reason this buggy behavior happens is because OSC is being too literal about user edits:

- When the user is moving a coordinate slider, the underlying backend is essentially calling `OpenSim::Coordinate::setValue`. This is correct behavior and probably closely mirrors (e.g.) OpenSim GUI. The user wiggling the slider around doesn't commit/re-realize the model
- When the user lets go of the coordinate slider, OSC interprets it as "the user is done editing **only** that coordinate value, go commit it to the modelstore". The underlying implementation then calls `OpenSim::Coordinate::setDefaultValue` (or similar) and re-initializes the model from scratch (OSC's guarantees are that each state of the model is "as if" the model were loaded from disk).

The second step of that procedure is incorrect. The reason it's incorrect is because editing one coordinate value *actually* potentially edits the other coordinate values via constraint satisfaction. OSC is assuming that the only change that should be saved to the model is the one the user is making. It does that, but it is then re-realizing the model *with only that edit*. This results in different solutions from when the user wiggles the slider (and, by constraint satisfaction, the other sliders) into a configuration.

To prevent the snapping, OSC should treat setting the value of one coordinate as *potentially* setting the value of all of them. This is because the user can "move" through multiple states while sliding things around with a slider smoothly whereas typing a value into the editor only instantaneously changes that one value - the difference might be causing the "snapping" effect (the source of this bug).

**Comment by adamkewley** [comment]
@JuliaVanBeesel the fix for this is now uploaded and should be built in the next couple of hours.

- Code changes (small): https://github.com/ComputationalBiomechanicsLab/opensim-creator/commit/409990ad5c826fbc4da27071fc250399da8f7273
- Build workflow that will contain the change: https://github.com/ComputationalBiomechanicsLab/opensim-creator/actions/runs/2840703501

**Comment by JuliaVanBeesel** [comment]
You are a genius @adamkewley! Thank you so much!

**Comment by JuliaVanBeesel** [comment]
Works splendidly! You are brilliant @adamkewley! Thanks!
