### ISSUE TITLE
Muscle plotting: Add Y padding to the curve

### ISSUE THREAD

**Issue by adamkewley** [ComputationalBiomechanicsLab/opensim-creator#364]
From @JuliaVanBeesel

> If possible, might also be good to leave some more space between the curve and the x-axis, sometimes the curves just disappears, like here.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/4730570/184938241-e77b94eb-70a0-4f0d-afae-c19f40ff1364.png)

I'm currently relying on autosizing from ImPlot [src](https://github.com/ComputationalBiomechanicsLab/opensim-creator/blob/1f37615dfba11eeaa0cedbdbabcd423cd1144807/src/Widgets/ModelMusclePlotPanel.cpp#L660), but I believe there's an appropriate function for adding the padding.

**Comment by adamkewley** [comment]
@JuliaVanBeesel : I added a ~5 % padding to the vertical Y component of the plots. Well spotted!

Demo image:

![Screenshot 2022-08-17 100943](https://user-images.githubusercontent.com/4730570/185068367-79199647-c8d4-460d-a06e-bbb7b08d6311.png)

**Comment by JuliaVanBeesel** [comment]
This looks much better! Thanks! :)
