### ISSUE TITLE
Fix mesh importer crashes when mousing over a complex mesh

### ISSUE THREAD

**Issue by adamkewley** [ComputationalBiomechanicsLab/opensim-creator#418]
From @JuliaVanBeesel

The `main`-branch version of the mesh importer will randomly freeze when the user is moving their mouse over a fairly complicated mesh.

I have the `.obj` files she was using, so I can hopefully reproduce it on my end.

**Comment by JuliaVanBeesel** [comment]
Were you able to reproduce this on your windows Computer? I can also test this on another windows Computer with the same files, if that would help.

**Comment by adamkewley** [comment]
@JuliaVanBeesel I wasn't able to reproduce it just yet - I was doing other stuff today, but I'll try and give it a look tomorrow.

The main thing for me is to be able to reproduce it with a debugger attached; otherwise, I'll have to harden the code (to print better error feedback) or get you to install a debugger :D

**Comment by adamkewley** [comment]
Still unable to reproduce this on my machine :( - even while running memory sanitizers etc. I'm assuming that this is some sort of extreme edge-case that's annoying to trigger.

 I'll create separate tickets for printing diagnostics etc. when crashes happen and maybe write some custom C++ that tries extreme stuff, like raycasting millions of points on the mesh etc.

**Comment by adamkewley** [comment]
@JuliaVanBeesel , could you try and trigger this bug on the latest build of OSC - it now contains some more crash reporting that may be able to shake out the issue.

If the application crashes with no error message, you can try opening the new crash reporting log. It's located in your user data director, which you can open via OSC through `about > user data dir`. The crash log will be called something obvious (e.g. `TIME_CrashReport.txt`)

**Comment by adamkewley** [comment]
After a call with Julia, I'm willing to conclude that this is a particularly tricky error to diagnose and the codebase will require a bunch of hardening checks to figure out why there's a problem.

- I can't reproduce the bug on my machine(s) (yet), so Julia has to exercise the repro
  - Running the repro on my local machine under Linux with memory sanitizers, etc. doesn't indicate an obvious problem (e.g. an out of bounds bug or similar)
- It isn't a deterministic crash: it happens randomly based on software usage and takes ~5-15 min of manual UI usage to trigger
- When it triggers, it doesn't trigger a fatal crash and/or exception: it only triggers a "busyloop-like" behavior, where the application just hangs
- Attaching a debugger only gives a stracktrace to `SDL_WaitEvent` in `App.cpp`, rather than where the bug is probably happening. Attempting to interrupt the application always ends up here.
- Taking memory snapshots doesn't indicate that the heap is growing, so I can't use heap snapshots to figure out which part of the codebase contains something illogical
- CPU profiling indicates that the UI is doing *something*; specifically, that it's rendering the UI. This is as expected, given the repro's scene, but there's no indication as to *why* it fails to update the UI

So:
- The application is still alive
- It isn't busylooping in an obviously-buggy location
- It isn't blowing up the heap
- And CPU profiling indicates it's behaving normally
- *But* the application is *clearly* hung and unusable

![Screenshot 2022-09-13 164148](https://user-images.githubusercontent.com/4730570/189936329-1c8c54de-ac48-4d9d-88f6-52e66c71c349.png)

Interesting :wink:

**Comment by adamkewley** [comment]
@JuliaVanBeesel when you're back, we should give this another try with a debugger etc.

Since the last session, I have refactored a bunch of code that (I believe - no hard evidence :() was causing the crash and I have added extra checks into the code to ensure that certain preconditions etc. are tested at runtime. Now might be a time to see if it's still crashing and then respond as necessary

(apologies for this dragging on: it's because I don't know *exactly* what is breaking)

**Comment by adamkewley** [comment]
Demoting + de-prioritizing this for now

This is a crash (very bad) but it only happens with extremely screwy meshes on very specific hardware.

To try and fix this crash I have:

- Reimplemented large chunks of OpenSim Creator's rendering API to ensure that it effectively does the same thing it was doing in 0.2.0 (assumed to be "fine"?): works on my test machine, still crashes on Julia's machine
- Hardened the OpenSim Creator rendering API with things like disabling unused shader attributes, bounds-checked buffer uploads, more assertions, etc.: works on my test machine, and is faster (yay), still crashes on Julia's machine
- Debugged the OpenGL calls using tools like `RenderDoc`

The implementation was tested on:

- An i5-11400 desktop /w NVIDIA 1060 GPU in Windows and Ubuntu20: no crash
- As above, but the Intel iGPU built into the i5-11400 (which should, in principle, have similar drivers to Julia's machine): no crash
- As above, but using Ubuntu20 with Mesa3D debug flags all turned on, so that the underlying OpenGL driver performs more checks/validation: no crash (minor texture enum bug found and fixed, but almost definitely unrelated)
- As above, but with Ubuntu20+Mesa3D+even more debug flags: no crash
- As above, but with libASAN enabled for SimTK, OpenSim, and OpenSim creator, to find memory corruption, leaks, etc.: no crash (but some minor leaks in OpenSim were found and noted)
- As above, but with libASAN turned into an even stricter check most: no crash (but it found a few edge-case global static initialization issues in simbody, which aren't a problem)
- As above, but switched libASAN for `valgrind`, which performs different memory corruption/leak tests: no crash (found the same leaks as libASAN)
- A Macbook Air 2020, which has a very similar iGPU to Julia's machine (Julia's: `Intel Iris Xe Graphics - 3.3.0 build 30.0.100.9955`, Air: `Intel Iris Plus - 4.1 INTEL-18.8.5`)

**Comment by adamkewley** [comment]
Note: Julia's hardware is:

> Intel Iris Xe Graphics
> Renderer: 3.3.0-Build 30.0.100.9955
> Shader version: 3.30 - Build 30.0.100.9955

**Comment by adamkewley** [comment]
This *appears* to be fixed. @JuliaVanBeesel used the latest version, and left it running overnight, without any further crashes.

The bug *appears* to be related to using `GL_RED` textures. For some reason, using arbitrarily-sized multisampled GL_RED render buffers might occasionally cause a crash on some Intel when drawing crazy meshes. This might be a bug in OSC (in the sense that there might be a rule somewhere that says that GL_RED textures must be aligned to 4-bytes, or something, or blitting GL_RED textures works differently), but I don't have the time to figure out *why* this is a bug.

Either way, it's fixed and will ship in the next release.
