### ISSUE TITLE
Selecting a geometry path point should highlight that particular point in the viewer

### ISSUE THREAD

**Issue by adamkewley** [ComputationalBiomechanicsLab/opensim-creator#425]
Spotted by @JuliaVanBeesel

Selecting a geometry path point through any means (e.g. hierarchy viewer, 3D visualizer, etc.) should highlight that particular point in the viewer, rather than not highlighting anything (or auto-selecting the whole muscle)

**Comment by adamkewley** [comment]
This is now implemented in the `main` branch.

Effectively, it highlights user-defined path points in the 3D viewer and also makes them click-able in the 3D UI (both features are tied together). So users can now just click on a path point and then wiggle it around with the new `-` and `+` buttons.

Great idea suggestion @JuliaVanBeesel

Screenshot:

![Screenshot 2022-09-01 093247](https://user-images.githubusercontent.com/4730570/187858269-cfff9c46-befd-4764-bd99-de902afd2889.png)

**Comment by JuliaVanBeesel** [comment]
Nice! That is so helpful! Thanks!
