### ISSUE TITLE
Fix "step by" right-click step buttons always converts to degrees even if clicking on radians

### ISSUE THREAD

**Issue by adamkewley** [ComputationalBiomechanicsLab/opensim-creator#643]
From @AdrianHendrik:

> (from @adamkewley : I wrote this based on a spoken conversation, it isn't exactly what was said, just what I remember)
>
> - If I am editing a wrap cylinder in the editor
> - and I use the property editor to edit the orientation/rotation of the cylinder
> - and I right-click the `-` and `+` buttons to bring up the menu that enables changing step size
> - and I click a radians button
> - then the step size is filled out as, and steps in, degrees
> - even if the input I'm editing requires radians

**Comment by AdrianHendrik** [comment]
My theory is that this issue is due to default expression for angles in .osim files being radians, while in OSC editors it is degrees. 
Since there is no toggle to change angle expression for wrapping surfaces (not yet?), inserted values will always be converted to degrees in OSC and those values will then be inserted without deg2rad conversion into the .osim file

Other elements which are able to rotate that do not have a toggle for radians and degrees (yet) might have a similar problem

**Comment by adamkewley** [comment]
The fix for this was to make the step size buttons a little bit more predictable.

Previously, the step-size buttons assumed the quantity is always in degrees and didn't even bother to inter-convert based on whether degrees or radians is toggled.

I thought about checking that flag (in the code, `m_OrientationValsAreInRadians`), but I have instead made it such that clicking a radian-based step size will always make the step size (e.g.) `pi`, even if editing in degrees, rather than trying to automatically inter-convert based on what the user clicked in a separate toggle button.

This means that the user has to be aware of what units they are editing in, because the UI isn't going to automatically  convert clicking a "radians' button into a degrees-equivalent step size. However, it makes the UI's behavior more predictable because pressing a step size always results in exactly that step being added/subtracted from the property (e.g. if you press `1 pi` you can expect that the step size will be `3.14...`).

The benefit of it being predictable, rather than automatic, is that it will still work predictably when confronted with OpenSim properties that are logically rotational but, have not been detected by OSC as rotational. This edge-case can happen because the OpenSim API doesn't explicitly "say" (to OSC) which properties are/aren't rotational. OSC has to hack around this limitation by using heuristics like "is the property called `orientation`". The reason why predictability is important is because users might expect a certain (automatic) behavior in these mis-identified inputs, but it won't apply in that case because OSC might not think of the property as "rotational". Imho, it's better that all inputs have the same behavior.
