### ISSUE TITLE
Weird coupling between camera movement and marker's scale factors

### ISSUE THREAD

**Issue by itbellix** [ComputationalBiomechanicsLab/opensim-creator#679]
Hi @adamkewley,
I think I found a minor bug that sometimes couples the scale factors in the scene with the movement of the scene camera. I have selected a marker in a model, and with the marker selected I was trying to change the scale factors for the markers in the model. If I use the arrows on the keyboard to "move around" in the scale factor field, then the point of view of the camera changes as well:
![image](https://user-images.githubusercontent.com/50029203/235439598-4bb35d4b-39fd-4831-911f-e9e59ce9f0dc.png)

![image](https://user-images.githubusercontent.com/50029203/235439705-0965034e-06f5-4ca2-ae06-d1d256b7d39d.png)

As you see, moving the position of the cursor' bar over the digits of the scale factor made the camera move as well.

**Comment by adamkewley** [comment]
Thanks for this bug report @itbellix - it has now been fixed in bb8c7c7
