### ISSUE TITLE
fatal error LNK1104: “..\..\src\OpenSimCreator\Debug\OpenSimCreator.lib”

### ISSUE THREAD

**Issue by iverson1github** [ComputationalBiomechanicsLab/opensim-creator#748]
Where is OpenSimCreator.lib？

**Comment by adamkewley** [comment]
Hi @iverson1github 

`OpenSimCreator.lib` is built as part of the overall OpenSimCreator build. The exact location for its declartion is:

- https://github.com/ComputationalBiomechanicsLab/opensim-creator/blob/main/src/OpenSimCreator/CMakeLists.txt#L6

The location of the `lib` file is dictated by where CMake put it while building (probably) `osc.exe` (the application executable).

What build commands etc. are you using to generate this error message? It looks like the build system hasn't first build `OpenSimCreator.lib` for you

**Comment by iverson1github** [comment]
I have fixed it. Because a ComponentRegistry.cpp' s code in the&nbsp;OpenSimCreator must be GB2312, so It succeeded in building. Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ComputationalBiomechanicsLab/opensim-creator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月15日(星期二) 中午1:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ComputationalBiomechanicsLab/opensim-creator] fatal error LNK1104: “..\..\src\OpenSimCreator\Debug\OpenSimCreator.lib” (Issue #748)





 
Hi @iverson1github
 
OpenSimCreator.lib is built as part of the overall OpenSimCreator build. The exact location for its declartion is:
  
https://github.com/ComputationalBiomechanicsLab/opensim-creator/blob/main/src/OpenSimCreator/CMakeLists.txt#L6
  
The location of the lib file is dictated by where CMake put it while building (probably) osc.exe (the application executable).
 
What build commands etc. are you using to generate this error message? It looks like the build system hasn't first build OpenSimCreator.lib for you
