### ISSUE TITLE
Can't build this project by running and building build_windows.py

### ISSUE THREAD

**Issue by iverson1github** [ComputationalBiomechanicsLab/opensim-creator#754]
Can't build this project by running and building. Because I run and build build_windows.py after removing the checkbox of "Beta version: Use Unicode UTF-8 to provide global language support" in the Win11 system's regional settings. I want to run and build in this case. How to fix it?

**Comment by adamkewley** [comment]
What do you mean? What error message do you have? What are you trying to run?

OSC sucessfully builds on three different computers with three different operating systems, and three different VMs worth of GitHub actions, and it does not (as far as I'm aware) use anything other than the ASCII subset of UTF-8.
