### ISSUE TITLE
Fix window appears to be very dark in >0.5.0 on Intel HD 530

### ISSUE THREAD

**Issue by adamkewley** [ComputationalBiomechanicsLab/opensim-creator#764]
Reported by @AdrianHendrik

The renderer is creating very dark renders on this specific hardware:

![MicrosoftTeams-image](https://github.com/ComputationalBiomechanicsLab/opensim-creator/assets/4730570/4bcf8f03-785a-471c-a8dc-36c0b09e0a9f)

The GPU is a little old (roughly 2015 release date - reported as 2955 days old or so), so it may be suggested that new drivers are installed - although, Intel dropped this range before they got around to implementing OpenGL 4.4, so it's probably an older driver range.

However, I'll use this opportunity to add any necessary detection code to OpenGL to try and report the problem to the user (and maybe have runtime fallbacks, but supporting older GPUs might not be worth it because Intel has really improved in the last 3 or 4 years).

**Comment by adamkewley** [comment]
Hi @AdrianHendrik, would it be possible for you to install this newer version of OSC:

https://github.com/ComputationalBiomechanicsLab/opensim-creator/actions/runs/6099949191

And copy+paste the log (there's a `copy to clipboard` button) to here? I've added some basic runtime checks to the OpenGL part of OSC to try and figure out exactly what the limitation is.

---

Additionally, if your laptop permits, could you try to install newer graphics drivers? The driver list for older graphics products is here:

- https://www.intel.com/content/www/us/en/support/articles/000005733/graphics.html
- (I believe yours will be `Intel HD Graphics 530` - self-service begins December 30 2022)

This is unlikely to fix anything--your driver is from late-2020, so it's not as old as the hardware (https://www.graphics-drivers.eu/drivers-for-intel-build-8853.html)--but it *might* fix it for you before I get a chance to figure out what changes I may need to make to OSC.

**Comment by AdrianHendrik** [comment]
Hi @adamkewley, I've downloaded the newer version.
Here is the log:

[info] enabling backtrace handler
[info] initializing main application window
[info] initializing OpenGL context
[info] OpenGL: the following OpenGL extensions may be missing from the graphics backend: 
[warning] OpenGL:  - GL_EXT_framebuffer_sRGB
[warning] OpenGL:  - GL_EXT_texture_object
[warning] OpenGL:  - GL_EXT_vertex_array
[warning] OpenGL: because extensions may be missing, rendering may behave abnormally
[warning] OpenGL: note: some graphics engines can mis-report an extension as missing
[info] OpenGL initialized: info: Intel, Intel(R) HD Graphics 530, (3.3.0 - Build 27.20.100.9416), GLSL 3.30 - Build 27.20.100.9416
[info] setting locale to US (so that numbers are always in the format '0.x'
[info] removing OpenSim's default log (opensim.log)
[info] attaching OpenSim to this log
[info] registering OpenSim types
[info] registering OpenSim geometry search path to use osc resources
[info] added geometry search path entry: C:\Program Files\OpenSimCreatorTest\resources\geometry
[info] showing screen class osc::MainUIScreen

**Comment by adamkewley** [comment]
Thanks for that @AdrianHendrik

Your GPU is reporting that it may not support sRGB framebuffers (`GL_EXT_framebuffer_sRGB`), which *may* be what is causing the darkness, but a separate check I added in 2079d4b is reporting that `GL_FRAMEBUFFER_SRGB` was successfully set, which might be a contradiction from the driver.

I have also previously seen that Intel GPUs can be a little bit spotty about reporting extension support (e.g. they'll report a GPU extension as missing but it's actually available), so I have made 2 new changes:

- Made the windowing system explicitly request an sRGB window before on-initialization, rather than after initialization (9b9d219)
- And make OpenGL spam out a list of all supported extensions (48ad707), so that I can see what, exactly, your GPU reports that it supports (sRGB should be supported by all OpenGL 3.3 compatible devices)
- And made the maximum log length longer (f1957f4f), to acommodate the spam (I may remove/reduce the spam later, but this is all still in the development branch)

Once those have built via GitHub Actions (1-2 hours), I'd like you to give it a spin:

- Check if the the darkness fixed (probably not, but worth an ask)
- Copy + paste the log from the updated build: it should contain a long list of supported extensions by your GPU

**Comment by adamkewley** [comment]
The latest round of changes are semi-related to this, but might actually make your life a little more annoying @AdrianHendrik 

I had to downgrade the OpenGL log messages from `warn` to `debug` in preparation for the 0.5.2 release. This is because I anticipate that users will start reporting bugs to me if they start seeing warnings in the logs (and many of these OpenGL warnings are spurious because some GPUs mis-report extensions).

---

So, starting at 6da0257 and beyond, OSC now supports a `log_level` parameter in its configuration file:

- https://github.com/ComputationalBiomechanicsLab/opensim-creator/blob/main/build_resources/INSTALL_osc.toml#L5

**However**, if you are installing OSC over an existing configuration then the configuration file may not be updated. This is because I don't want to overwrite any potentially-user-edited configuration files.

---

Practically, what this means is that, for OSC builds after 6da0257, to see OpenGL debugging messages then you'll have to:

- (on Windows): open: `C:\Program Files\OpenSimCreator\osc.toml`
- Anywhere near the top of the file, as long as it above a section (e.g. `[experimental_feature_flags]`), the line `log_level = "debug"` can be added to make OSC emit more information to the logs as it boots
- You can uncomment [this template](https://github.com/ComputationalBiomechanicsLab/opensim-creator/blob/main/build_resources/INSTALL_osc.toml#L5) as an example

Unfortunately, changing the log level via the UI (e.g. in the log panel) won't work in this particular case because the thing we want to debug (initializing OpenGL) happens *before* the log UI etc. is booted.

**Comment by AdrianHendrik** [comment]
After installing build f9ed1e9 and following your instructions it looks like the the gui has returned to its intended brightness. Here is a screenshot to compare:
![image](https://github.com/ComputationalBiomechanicsLab/opensim-creator/assets/62060565/ff557e89-96d8-498c-a698-2086003dc0ef)
(left: build f9ed1e9, right: older build)


Attached is the output log of the new build.
[OSC output build f9ed1e9.txt](https://github.com/ComputationalBiomechanicsLab/opensim-creator/files/12559610/OSC.output.build.f9ed1e9.txt)

**Comment by adamkewley** [comment]
Oh lovely @AdrianHendrik ! - what a weird bug!

I think that specific GPU requires saying sRGB specifically before the window is initialized, but it's great that it now works!

**Comment by adamkewley** [comment]
Thanks again @AdrianHendrik !
