### ISSUE TITLE
Fix drag & drop not working in mesh importer screen

### ISSUE THREAD

**Issue by adamkewley** [ComputationalBiomechanicsLab/opensim-creator#77]
High-prio: it's explicitly mentioned in the documentation but does not work
Estimate: 1h

Didn't work for a Windows user when they dragged their files (VTPs) into the mesh importer screen.

**Comment by adamkewley** [comment]
Appears to work fine on Mac OSX: needs further investigation.

**Comment by adamkewley** [comment]
Also appear to work fine on my Windows10 machine.

Although it was kind of annoying that bulk dragging+dropping didn't group the import into one undo/redo step (e.g. importing 10 meshes by shift-clicking stuff in windows explorer followed by dragging them in would create 10 undo/redo steps).  I hotfixed the code to batch the import in 17d0802 to handle that.

@mariska-wesseling for this particular bug, would it be ok if you can confirm that the steps I'm using for testing it match what you're doing on your laptop? I am:

- Opening OpenSim Creator (you can use v0.0.8-beta, from the UX session)
- Opening mesh importer
- Separately opening a windows explorer dialog
- Browsing to a directory on my filesystem where `.vtp` files are (not zipped!)
- Clicking, or shift-clicking, on the vtp files I want
- Holding the left-mouse button down, dragging the files into the OpenSim Creator window

If you try that and it doesn't work, then there could be something unusual going on. If it works fine then my guess is that that the vtp files may have been within the zip archive that the tutorial provides (e.g. Windows supports clicking a zip file an seeing the contents as-if they were unpacked on the HDD).

The software could maybe be modified to support zip drag-and-drops, but it requires a bit of integration (because it requires that OSC has in-built support for (de)compression).

**Comment by mariska-wesseling** [comment]
@adamkewley I tried it again and it seems to work fine now. I have no idea what went wrong before, possibly I was indeed dragging from the zipped folder.

**Comment by adamkewley** [comment]
Thanks for getting back on this @mariska-wesseling - I'll close off this "it's a high-prio bug that needs to be fixed right now" ticket and make a "it's a lower-prio concern that drag drop might have issues with other use-cases" issue to investigate this later on :)

**Comment by mariska-wesseling** [comment]
@adamkewley  I ran into this problem again. After installing the most recent version and starting it the first time, I could not drag & drop any files (multiple or single files). They were definitely not in a zipped folder. After simply closing and restarting it was working fine though.
