### ISSUE TITLE
Hovering over a file in the home screen doesn't display the whole file name

### ISSUE THREAD

**Issue by AdrianHendrik** [ComputationalBiomechanicsLab/opensim-creator#784]
When you have a model open with a file name that is too long to be displayed in the 'tab box', OSC will display the complete file name when you hover your cursor over the file name in the 'tab box'.
![image](https://github.com/ComputationalBiomechanicsLab/opensim-creator/assets/62060565/80928941-0f43-47d0-8fc8-24841e9da3d5)

This does not happen in the homescreen when you first want to select a file to open. This makes selecting the right file impossible certain cases.
![image](https://github.com/ComputationalBiomechanicsLab/opensim-creator/assets/62060565/0dc22bd7-4f6d-47a8-94a3-09d78917ae44)

I know you can always open the correct file by opening through your fileexplorer, but displaying the full name when hovering over the file would be nice QoL improvement.

**Comment by adamkewley** [comment]
Implemented in `main` and shall be released in the next release (>0.5.2)

Thanks again @AdrianHendrik !
