### ISSUE TITLE
Muscle Points move when changing sockets

### ISSUE THREAD

**Issue by JuliaVanBeesel** [ComputationalBiomechanicsLab/opensim-creator#828]
Hi Adam,
How are you doing?
I've been working alot together recently with some colleagues who've started using OSC and who highly enjoy it (especially the live graphs), greetings from them all :)
As always when someone is using your software in a way you rarely do, they find something that is not working as expected.
This time's observation comes from Oliver Demuth, a colleague who is currently testing my transformation matlab code (and found a couple of issues with it, of course). Here is what he's found:

> Another thing I noticed in OpenSimCreator is that you can display the position of the muscles in different frames via points. But if I change the parent socket, the absolute position in the reference is taken and simply inserted and the point flies through space. Would it be possible to take the position in the new frame, instead of the relative position to the original Reference Frame Origin?

I've shot a little video for you about it:

https://github.com/ComputationalBiomechanicsLab/opensim-creator/assets/110537115/c2226c6e-750b-4823-92a3-fecfd0121728

**Comment by adamkewley** [comment]
Ah, I see the problem @JuliaVanBeesel  - I can try and add an `Express In new Frame`-type functionality when resocketing muscle points. It should've been there in the first place!

**Comment by adamkewley** [comment]
Hi @JuliaVanBeesel , could you confirm what version of OSC you/Oliver are using? I've tried to reproduce this using the latest release (0.5.9), but it looks like it has the `Re-express in another frame` tick-box that I think Oliver would want (it effectively does the necessary maths to stop the point snapping around)

Here's  a video of my perspective:


https://github.com/ComputationalBiomechanicsLab/opensim-creator/assets/4730570/edca4795-661c-4278-9889-fb26c075d32c

**Comment by JuliaVanBeesel** [comment]
Oh sorry @adamkewley , I thought I updated recently, but I just checked and my OSC has the version 0.4.1 oO
I'll update now and will double-check again.

**Comment by JuliaVanBeesel** [comment]
Sorry @adamkewley , I didn't realize I didn't have the newest version installed. 
I've tested it again with the new version, and it works exactly like your video is showing. I'm closing the issue as solved :)
