### ISSUE TITLE
Cannot hide markers

### ISSUE THREAD

**Issue by tgeijten** [ComputationalBiomechanicsLab/opensim-creator#834]
Steps to reproduce:
1. Load model with markers
2. right click markerset -> Display -> Hide all markerset components
3. Nothing happens

**Comment by adamkewley** [comment]
Unfortunately, Marker visibility is dictated by a separate model flag, so there's a little toggle button in the toolbar in the top of the editor

**Comment by tgeijten** [comment]
Ok, thanks!

 

To avoid confusion for future users, perhaps remove the menu item or link it to the toolbar button?

**Comment by adamkewley** [comment]
> To avoid confusion for future users, perhaps remove the menu item or link it to the toolbar button?

Good idea :> - maybe disabling the button with a tooltip along the lines of `this won't do anything, but maybe you can use bla bla bla` is enough to steer people in the right direction!
