### ISSUE TITLE
[Feature Request] jump to the selected item in Navigator tab

### ISSUE THREAD

**Issue by mrrezaie** [ComputationalBiomechanicsLab/opensim-creator#908]
Hi, when I select an object in viewer window, the navigator unfolds, but doesn't jump to the selected item, and I have to scroll the navigator to see it. Please see this:

https://github.com/user-attachments/assets/3d10580b-f113-4747-9bce-81b0231bb200

OSC 0.5.13
Sorry if I couldn't explain it properly, and thank you in advance.

**Comment by adamkewley** [comment]
Understood - I'll have a look into it (there's some internal APIs etc. available to set the scroll position, but I'll have to check how they work).

**Comment by adamkewley** [comment]
@mrrezaie , this is now implemented in the `main` branch and (I hope) has the expected behavior. Example:


https://github.com/user-attachments/assets/decf3db4-a328-4bc6-b5db-e28ef5b64811

**Comment by mrrezaie** [comment]
It seems perfect, and I appreciate your time and effort. Thanks a lot @adamkewley.
