### ISSUE TITLE
The selected and the hover object are shown in the same yellow color

### ISSUE THREAD

**Issue by mrrezaie** [ComputationalBiomechanicsLab/opensim-creator#916]
Hi, in this example, I selected the RLFC marker and then, I hovered over the RTB1 marker. But both of these markers are distinguished with yellow color in the Navigator pane.

![image](https://github.com/user-attachments/assets/0dc70d81-b910-4c6b-8daf-96fc027effaa)

It would be great if one of them gets a different color. Thank you.

**Comment by adamkewley** [comment]
Fixed in d771b47, should be available in the next release (approx 1-1.5 months), or in the next green build on the actions page:

- https://github.com/ComputationalBiomechanicsLab/opensim-creator/actions

Thanks again @mrrezaie
