### ISSUE TITLE
A few visualization issues

### ISSUE THREAD

**Issue by mrrezaie** [ComputationalBiomechanicsLab/opensim-creator#919]
Hi, sorry for opening another issue. There are a few issues merely about visualization:

1. The name of the parent frame of the muscles points are not displayed.
2. The same for ligaments 
![image](https://github.com/user-attachments/assets/7b852f37-d062-45ef-9162-5049eb961741)
4. When hovering over ligaments, the name and the class names are not displayed (this is correct in muscles).
![image](https://github.com/user-attachments/assets/643ae889-dadb-4315-905f-198b4011dafd)

Thank you in advance.

**Comment by adamkewley** [comment]
@mrrezaie , points 1 & 2 were fixed in #916. You will need to download a build from the actions page to see this (explained there).

I have fixed the ligament hittest issue, which should also become available whenever a green build gets through the pipeline.

Thanks again
