### ISSUE TITLE
Add option to reset all coordinates to their default position

### ISSUE THREAD

**Issue by tgeijten** [ComputationalBiomechanicsLab/opensim-creator#957]
I often want to reset the pose the default (usually that means all coordinates set to 0), but at the moment it seems I have to check the coordinates one-by-one and set them to zero by hand.

Would be great if there's an easier way to do this, e.g. a "reset" button at the top of the coordinates window.

**Comment by adamkewley** [comment]
Seems like an easy enough change, I can try and whack this in in the next release (which, hopefully, will be sometime next week or so).

**Comment by tgeijten** [comment]
That looks great, thanks!

In addition to "zero all coordinates" you might also add "set to default values", using the `default_value` defined in the model Coordinate section. These are usually zero but can be anything.

**Comment by adamkewley** [comment]
No problem!

In the case of the OSC editor, the only thing that's ever being edited is the `default_value`s. It's why saving the model also saves the pose. #783 would need to be fixed/implemented in order for a pose defaulter to work?

**Comment by tgeijten** [comment]
Aha, you mean the current pose is saved automatically using the `default_value`s? In that case, it would indeed not make much sense unless #783 is changed, and a pose management system similar to OpenSim is implemented.

In any case, having the option to zero the coordinates is already a huge improvement -- I can now just press this button before saving, instead of going through all the coordinates by hand 😄

**Comment by adamkewley** [comment]
Good to hear :smile: - sorry that #783 isn't done yet, but it is going to require an overhaul to a fairly core datastructure, and it's being kicked back because I'd also like to handle a few other fundamental issues with the document API (e.g. no multiselect, hard to manage multiple models/motions in a single scene, etc. etc.)
